---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAM9ty7D7qqorn/B2LK9J4sIwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjEwNjI2MDAyNzAwWhcNMzEwNjI0MDAy
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABLRBCmygZ2CjhNLQDlsjkLUlvjXaqGRgBORW0IHjENXr0IWZ0KptFQhv
          ZlI99xMtSyVF5RhYv8oVz0fXpCYfiAajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgF2vISemnVeyPTQHcVMHzR02NXYuwVfmNfU2fPpnjarMwCgYIKoZIzj0E
          AwIDSAAwRQIgHXgN6H0kDi8HeoMIbInctVbuTyoNEkPsb5U16/JBQhcCIQDqmIdw
          mTLOA0I7AtqbP8JSy3XdQDfRTin7vZDJvb5lyA==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUDCCAfegAwIBAgIQfbfdnBVjbb9MkC7+FLStozAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yMTA2MjYwMDI3MDBaFw0zMTA2MjQwMDI3MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          WEaVJm/UmZt2LVEEEUnf+ynTrusiUb4eNQKkv+wdv7t2CYTCOJcxFCDg9tEHCZov
          lBqfCIBarLr8RJ6C6lO+raNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCf
          0qhbuWlno1aJ/AyZRuUUE5Vr73P9tN2s7TREJoPiAjAKBggqhkjOPQQDAgNHADBE
          AiByZPYV5Zbaeyuv6XnYUytM7JLzL9UQBp5RyS1cMNkA3gIgXP/AI8nImJDrRCz5
          N29Cv1pSaqBF46BdNS6DCbYuhHc=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
