---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICWDCCAf6gAwIBAgIRAJif7PhkHyCAcjYV3Pv63dEwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjEwNjI2MDAyNzAwWhcNMzEwNjI0MDAy
          NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABFocyeAQ/z1PRTpN9ohrTebBrZRPk/AcwDkSRG57nhjSG8N9fvi6JIeh
          K15AOAfHZfjU5vkgDrwuW1xRD5wPAzmjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQg894C/tRyg62ndRgluFg76U5ely8L/OobhaC/qhTqlXgwCgYIKoZIzj0E
          AwIDSAAwRQIhAMSdR79CrEcNnCfjnnNtRb3wBU/FY8ylsgkcuAlLzzmQAiBqg20R
          EuhyatFH/a5ofUzKypmWkQl7aD82Uk15fsiG2Q==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQHJt8teKPod6bfp5AN2IK1TAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yMTA2MjYwMDI3MDBaFw0zMTA2MjQwMDI3MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          Shi9gtKYMLGhgwptLtQ3kX6jwVFZoHtq5BwHm4EI11BSa6HDHLJnvM5YDwEDPqcp
          Mm6VtkU/BcvE6/Qhm92gWqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDH
          dMNygD6rzyhDq1yTDy0opLBrbih1lrJn/O8nT4BEgjAKBggqhkjOPQQDAgNIADBF
          AiAKlygIJzWRps+uv7RZ07pZB0Gg5T04qsKBhmCL4Y0zDwIhANKylcweuvum5TD3
          egdKCbEg5G+8q8/wmUmUQturFD3m
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
